var GTA = {"name":"GTA",
"2014-06":{"neg":[["4.49","I liked a @YouTube video from @bengamingz http://t.co/iQw86Sp9ix Im Not A Hipster GTA V 1.14 New Cars-New Paint jobs-Weapons-&amp; more","BengamingZ",],
["4.41","I liked a @YouTube video from @fantastical_g http://t.co/VavvhBaN7c GTA 5 Mods - How To \"Mod ANY Vehicle\" (Mod ANY Car In GTA 5) [USB","BengamingZ",],
["4.08","RT @RockstarGames: Wow. The Terminator 2 truck chase seen remade shot-for-shot in #GTAOnline by @Droopy1943 http://t.co/PAyibgHhzo","ChrisJP88",],
["2.92","So battlefield is going to have heists before GTA Online? Hmm... wtf?","ECHODIVISION5",],
["5.0","Guys I just owned everyone on gta I was on fire","freakypancake",],
["1.89","Well gta just crashed that sucks because I almost reached rank 250 I needed like 50more rp dissent that suck","freakypancake",],
["2.28","I\'m going to eat a five scoop chocolate ice cream cone I may throw up after I eat it don\'t ask why I\'m eating it I just lost a bet on gta v","freakypancake",],
],
"neutral":[["5","Im Not A Hipster GTA V 1.14 New Cars-New Paint jobs-Weapons-&amp; more: http://t.co/iQw86Sp9ix via @YouTube","BengamingZ",],
["5","RT @gamespot: The producer of GTA is buying a church for the Edinburgh community. http://t.co/3czRx021ko http://t.co/ledj6u5YKH","DeathlightC7",],
["5","RT @PlayStation: #GTAV on PS4 coming this fall. Watch the all-new trailer in 1080p at http://t.co/q7GbX6xURf","DeathlightC7",],
["5","RT @eurogamer: Morning! ICYMI, Grand Theft Auto 5 is coming to PC, PS4 and Xbox One this autumn: http://t.co/k2FyZnwuVl http://t.co/QK4cLvQ…","DeathlightC7",],
["5","Just got done recording gta v online","freakypancake",],
],
"pos":[["6.77","I liked a @YouTube video from @i_am_wildcat http://t.co/1xU91Our06 GTA 5 Online Multiplayer Funny Moments 5 - KYR SP33DY and The","BengamingZ",],
["5.66","@jadesharp1992 Hi Jade. Just letting you know an update to GTA Cheats is out now, should fix those problems you had with VoiceOver :)","ChrisJP88",],
["6.07","RT @LatestPS4: VIDEO: Grand Theft Auto V compared on PS4 and PS3 http://t.co/aFWhcLoNw7”","DeathlightC7",],
["6.21","RT @Gam3Newz: Sony Teases Something Exclusive for Grand Theft Auto V PS4 - http://t.co/yDlT7Znfv6 - pslifestyle","DeathlightC7",],
["6.71","RT @gamespot: GTA 5 for Xbox One, PS4, and PC has increased draw distances, better resolution, new wildlife. http://t.co/r8iwQGdI9k http://…","DeathlightC7",],
["6.48","RT @pushsquare: E3 2014: How Much Better Does Grand Theft Auto V Look on PS4? http://t.co/CYYLKFk25f #PS4 #RockstarGames #GrandTheftAuto","DeathlightC7",],
["5.64","The not a hipster update on gta v is awesome and I\'m not a hipster on there nudge nudge wink wink ; )","freakypancake",],
],
},
"2014-09":{"neg":[["4.48","I added a video to a @YouTube playlist http://t.co/CrfOi6epxZ GTA V gameplay 1","BengamingZ",],
["4.03","I added a video to a @YouTube playlist http://t.co/i4nLAfUSOw GTA V Stunt Montage 2","BengamingZ",],
["4.68","I added a video to a @YouTube playlist http://t.co/bX7icGFN9U GTA V High Life Update Car-Pegassi Zentorno","BengamingZ",],
["4.3","I added a video to a @YouTube playlist http://t.co/yY3gho9WMy GTA V Unlimited Money Glitch After Patch 1.16 Fast &amp; Easy","BengamingZ",],
["3.61","I added a video to a @YouTube playlist http://t.co/DfhAAowTK7 GTA V FAIL MONTAGE","BengamingZ",],
["3.45","Just focus and take things slow. Forget the negativity. #needagoodlongtalk","heyacallmejessa",],
],
"neutral":[["5","I added a video to a @YouTube playlist http://t.co/pQvGtQT7qD Best GTA V Solo money glitch after patch 1.12","BengamingZ",],
["5","GTA V Unlimited Money Glitch After Patch 1.16 Fast &amp; Easy: http://t.co/yY3gho9WMy via @YouTube","BengamingZ",],
["5","I added a video to a @YouTube playlist http://t.co/GGOgAXT2FS GTA 5 Business update \"new cars\" new weapons\" a new plane\"","BengamingZ",],
["5","I added a video to a @YouTube playlist http://t.co/jlE4eeUN8y Im Not A Hipster GTA V 1.14 New Cars-New Paint jobs-Weapons-&amp; more","BengamingZ",],
],
"pos":[["6.47","I added a video to a @YouTube playlist http://t.co/jJ0bAPbxai GTA V Stunt Montage 3 [GTA V STUNTS] EPIC - AMAZING - AWESOME","BengamingZ",],
["6.39","GTA V Stunt Montage 4 [GTA V STUNTS] EPIC &amp; AMAZING!: http://t.co/OnmuC8hFRV via @YouTube","BengamingZ",],
["5.46","I added a video to a @YouTube playlist http://t.co/PczHjLop1i GTA V Stunt Montage 5 [GTA V STUNTS] AMAZING - EPIC","BengamingZ",],
["5.18","I added a video to a @YouTube playlist http://t.co/C8IwVz0KGj GTA V Unlimited Money Glitch After Patch 1.13 Fast And Easy","BengamingZ",],
["5.53","I added a video to a @YouTube playlist http://t.co/OnmuC8hFRV GTA V Stunt Montage 4 [GTA V STUNTS] EPIC &amp; AMAZING!","BengamingZ",],
["6.27","GTA V Stunt Montage 5 [GTA V STUNTS] AMAZING - EPIC: http://t.co/PczHjLop1i via @YouTube","BengamingZ",],
],
},
"2014-08":{"neg":[],
"neutral":[["5","GTA V Modded Lobbies - Unlimited Money - Flying Cars: http://t.co/k4HAZWf2B3 via @YouTube","BengamingZ",],
],
"pos":[["7.43","GTA V Stunt Montage 3 [GTA V STUNTS] EPIC - AMAZING - AWESOME: http://t.co/jJ0bAPbxai via @YouTube","BengamingZ",],
],
},
"2015-01":{"neg":[["3.34","@tra5her Will be soon. Personally I feel like they\'re more of a hassle to enter that way, shame they\'re not saved in the phone like GTA IV.","ChrisJP88",],
["3.15","@schillingc that was meant as a response to your other tweet. It wasn\'t Skyward Sword or GTA IV.","davescarborough",],
["2.09","PC release of GTA5 was delayed until  the end of march? Sure its better to have it delayed than it being bad but they sure announced it late","ForceCommander",],
["4.58","Who says real life isn\'t like a videogame? http://t.co/qLbrzmxGtA","JaySevenZero",],
["2.65","I\'m up and ready to fuck shit up but on what game? GTA or CoD?","MLG_Sperks",],
["4.2","Bout to hit up some GTA online HMU if you wanna join me (I\'m level 72)","MLG_Sperks",],
["2.75","RT @TinyPixelBlock: \"We don\'t want to censor any games.Just GTA V.And Hatred.And Huniepop.But they need it. Trust me.\"Yeah, not buyin…","NotOtsdarva",],
],
"neutral":[["5","RT @VideoGamerCom: #PowerFriday returns! To celebrate here\'s your chance to win GTA5 &amp; Alien: Isolation stuff. Follow and RT to enter! http…","Alpha118",],
["5","RT @Proasheck: oh wow they delayed gta v on pc until the exact same day that martin mcfly goes to the future","Alpha118",],
["5","@cowfishdreams @Ace_McDunk Sunset Overdrive, Minecraft and then maybe wait for Quantum Break reviews, failing that GTA or Destiny","Alpha118",],
["5","Seniors react on GTA V http://t.co/dIvf3t84Wh","Eftimin",],
["5","RT @gamespot: See how the world of Los Santos in #GTAV stacks up against LA with side-by-side images. http://t.co/ZFR6FVoncI http://t.co/qP…","mix_martes86",],
["5","#GTAOnline all day today.","guitar_guy715",],
],
"pos":[["6.7","Elders Play Grand Theft Auto V (Elders React: Gam…: http://t.co/gOiXxWytZU @JamesDrenning @BrittMcCroskey 😂","_SweetSurrender",],
["8.51","@dudettecolette GTA V, a bit of Dragon Age multiplayer and surprisingly good PvZ Garden Warfare","Alpha118",],
["5.39","@TheJTRO maybe man, that is until I win the lottery and write the script/screen play for GRAND THEFT AUTO: the movie #totallyhaveacameo","jova7587",],
["6.98","RT @WagTanga: You deserve to be happy.","KobeeMalay",],
["5.93","RT @WagTanga: When you truly care for someone, their mistakes never change your feelings because it\'s the mind that gets angry but the hear…","KobeeMalay",],
["5.6","RT @DaithiDeNogla: GTA 5 Online Funny Moments - Late Christmas, Bad Luck Daithi, Snowballs Fun!: http://t.co/jenUIaDzNC via @YouTube","RageKage5000",],
["5.87","RT @VG247: #GTA5 looks a lot like Limbo without textures http://t.co/dAtbJXnlS3 http://t.co/kUmHiyfh7s","CwwKeeler",],
["7.57","RT @RockstarGames: #GTAV fans continue to share some phenomenal photos through Snapmatic: http://t.co/qt6iNFY5nD http://t.co/W7E1pE2IuR","thedansinator",],
],
},
"2014-12":{"neg":[["3.61","GTA San Andreas 2 already?Wtf @RockstarGames","_Stef97",],
["3.12","PSN is back up but gta v servers are not 😔😔 well I hope that\'s the last from lizard squad for a while or I might just stick to pc gaming lol","BengamingZ",],
["3.93","In which I have a formidable backlog of games. Halo, GTA V, Far Cry 4, Super Smash Bros., Little Big Planet 3....yeah, I\'m good.","EdsHead",],
["2.41","Online in GTA V:Guy: Are you from TN too?Me: No. I\'m from MN.Guy: To be honest, I don\'t know where that is. It\'s in the northeast?WTF?","evild70",],
["2.08","Anyone willing to a crap driver* win some races in GTAV so they can upgrade their transmission?*by this I mean me!","JaySevenZero",],
["3.08","RT @caraellison: I still can\'t get over that GTA V isn\'t on sale in Australian Target but Call of Duty toys for 10 yr olds are http://t.co/…","JaySevenZero",],
["3.76","Anyone on GTAV (PS4) willing to help me win some races so I can get my upgraded transmission?","JaySevenZero",],
["3.36","I added a video to a @YouTube playlist http://t.co/oWqCe1qRPO GTA 5 - How to Make $2.1 Billion","lambasolid",],
["2.05","@rockstarsupport rebooting my xbox didn\'t really help i just want to play #gtaonline but i can\'t and will now miss out :(","RageKage5000",],
["3.25","RT @Nwllsn7: @Domislive hey dom, I hope you get your channel back, I miss my daily GTA videos, two times a day. You have my support man","RageKage5000",],
["4.18","Thankfully anti-#GamerGate was able to ban GTAV. Imagine the fun people could have if it were still sold, sickening to a #GamersPlus like me","Outlets_",],
["2.78","RT @Totalbiscuit: Solved the problem of killing prostitutes in GTA5. Turns out it was quite easy. All I had to do was, not.","Outlets_",],
["4.03","Ban GTAV it hurt my feelings #GamerGate","Outlets_",],
["4.04","RT @YungPineapple_: \"NO MORE CROSS MULTIPLYING JUST CROSSING THESE NIGGAS UP\" http://t.co/uGtAz3ABRK","SlimyGibbon",],
],
"neutral":[["5","GTA V Stunt Montage [GTA V STUNTS]: http://t.co/BQOeUqHpim via @YouTube","BengamingZ",],
["5","RT @caneandrinse: EPIC GTAV GAME NIGHT UPDATE, Sunday 28th Dec. See thread for further details: http://t.co/6Y8htEeaHS http://t.co/Ar29G9Z7…","JaySevenZero",],
["5","RT @caneandrinse: EPIC GTAV GAME NIGHT on the PS4 8pm 28th Dec.Interested? Then see our forum thread for further details - link below:htt…","JaySevenZero",],
["5","RT @gamespite: Dear Nintendo, please license the GTA V water engine and make a new Wave Race.","joeldawson83",],
["5","@icrazyteddy teddy we have a crisis in the gta community in that some of us cannot play gta online with the new update the game lags alot","RageKage5000",],
["5","Yet again @Rockstargames fail to sort out their cloud servers so no playing #gtaonline for me this xmas to play the new dlc","RageKage5000",],
["5","@JustRiggz we need a kickstarter to get Turbid on Gta V","JetLife091",],
],
"pos":[["5.5","RT @Kotaku: One GTA V player\'s absurdly cool plane stunts: http://t.co/Z9pTB5V3W0 http://t.co/xzjt2clnru","Agonista",],
["5.09","I famosi \"GTA moments\"... http://t.co/jMmJJNXfEj","Agonista",],
["7.79","@h2odelirious hey dude have you and your friends got the #xmasgtadlc ?? i think y\'all would love it and love your vids dude :)","RageKage5000",],
],
},
"2014-04":{"neg":[["3.96","I liked a @YouTube video from @enragedcinema http://t.co/DsCZOq3420 GTA5 | How to Fix Error \"CANT SELL CARS OVER 50k\" &amp; Sell ANY Car","BengamingZ",],
["4.79","I liked a @YouTube video from @enragedcinema http://t.co/Bf8PgrmOo1 GTA5 | 100% Working Sell Super Cars Full Price 1.11 - 740k Every","BengamingZ",],
["4.08","Latest GTA Cheats app update only took 1 day for review! Wish Apple were always this fast. #iosreviewtime","ChrisJP88",],
],
"neutral":[["5","RT @channingtatum: What better way to start writing #MagicMike2 than with my old friend Dallas? #runatribe http://t.co/RalS3nQfro","RockiRacoon",],
],
"pos":[["6.81","I liked a @YouTube video http://t.co/vIHSpyhShY GTA 5 Online: NEW \"UNLIMITED MONEY GLITCH\" AFTER PATCH 1.12 BEST METHOD(GTA V 1.12","BengamingZ",],
["6.06","I liked a @YouTube video http://t.co/MUvRUAjWf3 GTA 5 Online: BEST SOLO \"UNLIMITED MONEY GLITCH\" AFTER PATCH 1.11 (GTA V New 1.11","BengamingZ",],
],
},
"2014-10":{"neg":[],
"neutral":[["5","RT @TheStrippin: Lindsay Lohan trying to sue GTA V because she claims the girl on the front cover is her. HAHAHAHA oh fuck. Don\'t flatter y…","Aj_Phrost",],
],
"pos":[["8.45","@BriaKelly oohhh you\'ll love it :) best gta next to san andreas :)","_SweetSurrender",],
["7.81","I liked a @YouTube video http://t.co/SXzjzGTAuy ARE YOU HAPPY NOW?!","Beast_Man101",],
["6.35","GTA V Stunt Montage Besra Stunts - Epic - Amazing: http://t.co/nphyzmIgda via @YouTube","BengamingZ",],
],
},
"2014-11":{"neg":[["2.89","@rds999_ my gamestop didnt have enough preorders for gta and lbp.. so i gotta wait till tomorrow 😠😠😑😑😢😢😢😭😭😭😔😔😔","_SweetSurrender",],
["4.91","I never had much desire to play GTA games in first person. But this trailer has changed my mind, it looks awesome! http://t.co/LzeLOZWguI","ChrisJP88",],
["3.73","GTA V in 1st peson mode? YES &amp; PLEASE. Looks like a completely different game. And now you can be Trevor, not just watch him be a psycho.","EdsHead",],
["1.05","RT @ShootBarrel: Feeling bad about accidentally killing that cat in GTA. Suddenly a \'Pay Respects\' button isn\'t such a stupid idea... http:…","EmperorRadish",],
["2.37","Too damn old and too damn cold for me to stand in line for GTAV &amp; FC4 tonight. Pick up after work tomorrow and it will be on.","papernut",],
],
"neutral":[["5","@keennddyy @AngieFaSho @iLadySwoop why not black friday ?? They have bundles. Either ps4 with the last of us and gta5 foe 399","_SweetSurrender",],
["5","RT @Gam3Newz: GTA Online Heists coming to all platforms “soon” says Rockstar - http://t.co/mflF49MXo2 - vg247 http://t.co/bQtARfL1IC","JHogan1994",],
],
"pos":[["7.04","RT @TheGTAPlace: New @TheGTAPlace exclusive screenshot for new-gen #GTAV! Thank you @RockstarGames! Others at http://t.co/BIZMG3vTS8 http:/…","ChrisJP88",],
["8.18","RT @TheGTAPlace: Cheers @RockstarGames you guys are amazing! http://t.co/HKmBYtkaaM","ChrisJP88",],
["5.38","Plenty of gaming between Halo MCC and GTA V on Xbox One in next few weeks. Can\'t wait. #whatsoldisnewagain","EdsHead",],
["6.29","RT @GassiTheCat: This was surely the first GTA *and* it was handheld. Had to use your imagination for cars + pedestrians #retrogaming http:…","EmperorRadish",],
["5.38","RT @SignedInPodcast: Episode 153: Far Cry 4, Assassin\'s Creed Rogue, CoD Advanced Warfare, This War of Mine, GTA V &amp; MORE! http://t.co/fASl…","evild70",],
["8.69","@Sonicfan00715 @AllGameBot The best soundtrack in a GTA... what memories...","MattOHaira",],
["5.61","RT @Sonicfan00715: my favorite gta game #retrogaming #GamersUnite #PS2 http://t.co/kVifGpOFWL","MattOHaira",],
],
},
"2014-01":{"neg":[],
"neutral":[],
"pos":[["5.02","I liked a @YouTube video from @bengamingz http://t.co/4n1CwNyQQq GTA V FAIL MONTAGE","BengamingZ",],
["5.99","I liked a @YouTube video from @bengamingz http://t.co/vBxVi6q4E8 GTA V gameplay 1","BengamingZ",],
["6.23","I liked a @YouTube video http://t.co/pAG3NcMOHx Tank I Los santos customs gta v ep 1","BengamingZ",],
["6.92","I liked a @YouTube video http://t.co/mPpFAuKXP5 GTA 5 Online: DNS CODES WORKING AFTER HOTFIX 1.09!!!","BengamingZ",],
],
},
"2014-03":{"neg":[],
"neutral":[["5","GTA 5 Business update \"new cars\" new weapons\" a new plane\": http://t.co/Rion2hNp8F via @YouTube","BengamingZ",],
["5","GTA 5 Business update \"new cars\" new weapons\" a new plane\" (+playlist): http://t.co/Mr4uOwOf84 via @YouTube","BengamingZ",],
],
"pos":[["6.2","I liked a @YouTube video from @bengamingz http://t.co/Yat6uBRXsR My New Lamborghini In GTA V","BengamingZ",],
["6.58","@wardneymartins Hey, are you still interested in helping to translate GTA Cheats? Please see http://t.co/fb2GrKzGRI","ChrisJP88",],
],
},
"2014-02":{"neg":[["4.93","I liked a @YouTube video from @jackkstevo http://t.co/NyfVME6WAq GTA 5 ONLINE: 1.10 NEW UNLIMITED RP &amp; MONEY INSANE RACE (EARN","BengamingZ",],
],
"neutral":[["5","Bengamingz shared the Grand Theft Auto V photo South Mo Milton Dr #GTAV http://t.co/m4FvBTTqoE http://t.co/aRqpEIctrO","BengamingZ",],
["5","@RockstarGames can u get rid of the #Parachuting on @GtaOnline and sort out the #jobs too where you can choose any vehicle to race with","RageKage5000",],
],
"pos":[["5.49","I liked a @YouTube video from @murderlikedj http://t.co/qmlmZn2AvU GTA 5 Online - Duplicate &amp; Store Any Vehicle In Your Garage! After","BengamingZ",],
["6.84","I liked a @YouTube video from @h2odelirious http://t.co/d78cirWY0D GTA 5 Online Funny Moments Ep. 26 (Playing with subscribers)","BengamingZ",],
],
},
"2014-05":{"neg":[["4.89","RT @jeffgerstmann: I feel like a lot of humanity\'s problems could be solved by an HD remake of GTA: San Andreas with modernized control opt…","videodiscthings",],
],
"neutral":[["5","GTA V Unlimited Money Glitch After Patch 1.13 Fast And Easy: http://t.co/IHOEG8pah6 via @YouTube","BengamingZ",],
["5","Best GTA V Solo money glitch after patch 1.12: http://t.co/pQvGtQC4oD via @YouTube","BengamingZ",],
["5","GTA V to  Skyrim: the ten most beautiful walks in gaming http://t.co/TO7l6gHNlP via @guardian","videodiscthings",],
],
"pos":[["6.73","I liked a @YouTube video from @mrjamesgeary http://t.co/dn7WOTG9Bu GTA 5 Online: SECRET Crew Colors - Neon, Gold, Kifflom &amp; More!","BengamingZ",],
["7.02","I liked a @YouTube video from @fantastical_g http://t.co/EhtINvX5cQ GTA 5 Online - Best RARE Paint Jobs! Car Customization Guide (GTA","BengamingZ",],
["5.53","I liked a @YouTube video from @bengamingz http://t.co/uPcPkMLInr GTA V High Life Update Car-Pegassi Zentorno","BengamingZ",],
["5.78","I liked a @YouTube video from @bengamingz http://t.co/pQvGtQC4oD Best GTA V Solo money glitch after patch 1.12","BengamingZ",],
["8.24","@Lawrencebaoo @minliangtan @Razer Always bring your baby\'s(Razer Blade) wherever you go :)","KobeeMalay",],
],
},
"2015-02":{"neg":[["4.26","RT @KyleDawg_: I feel bad for hating on GTA V these past years. I\'ve only truly noticed how crazy and well done the game is.","Alcoholikaust",],
["4.11","RT @gameinformer: Take-Two Has A Strong Fiscal Third Quarter, But Can\'t Match 2014\'s GTA-Powered Results - http://t.co/VGDpXRVN4H http://t.…","CwwKeeler",],
["3.79","RT @IGN: Grenade baseball? Here are 6 things we\'re doing in GTA V while waiting for Heists: http://t.co/PuSDwGLTK9 http://t.co/Q2yo6dGdSe","thedansinator",],
],
"neutral":[["5","@GAF_Hoje0308 same for Dre\'s Detox and GTAV heists. lmao","Alcoholikaust",],
["5","@KyleDawg_ @NeoGAFNewThread @GuerrillaDawg that killer whale strike in GTAV... shivers","Alcoholikaust",],
["5","RT @IGN: With #GTA5 and @Borderlands, Take Two is having an incredibly strong fiscal year http://t.co/xYO14A8Sys http://t.co/2oG48czlQL","thedansinator",],
["5","RT @TypicalGamer: GTA 5 CLOWN ZOMBIE TOWN! w/ @HikeTheGamer, @Team0Epiphany &amp; @Siefe! COME WATCH! :D https://t.co/gULammCV7S http://t.co/XD…","thedansinator",],
],
"pos":[["7.35","RT @Green9090LP: Friendly reminder not to pre-purchase PC ports like GTA V. They\'ll still be there after you know whether they work. And on…","KitSnowfox",],
["7.03","RT @GTAVoclock: GTA V o\'clock: \'Zombie Town\' &amp; 9 more creator jobs. Plus GTA 6 and Heist release date rumours http://t.co/mUC6r8zYn1 Enjoy!","thedansinator",],
["7.38","RT @IGN: .@RockstarGames has shipped an incredible 45MM copies of #GTA5  http://t.co/3adXkRlv1G http://t.co/u1hkDLRDES","thedansinator",],
["5.46","RT @RockstarGames: “Max Pun #2” – the latest parody by the always clever @8Bit_Bastard troupe https://t.co/4PTamrkadP  #GTAV #MaxPayne","thedansinator",],
],
},
"2014-07":{"neg":[],
"neutral":[["5","GTA V Stunt Montage 2: http://t.co/i4nLAgd22E via @YouTube","BengamingZ",],
["5","RT @wilw: The driver in the high speed chase has clearly never played GTA V.","KevEisler",],
["5","RT @agentbizzle: Lindsay Lohan is suing the makers of GTA V, claiming that they stole her likeness for a character. She is 100% right. http…","ShinnRyan",],
],
"pos":[["5.13","I liked a @YouTube video from @bengamingz http://t.co/i4nLAgd22E GTA V Stunt Montage 2","BengamingZ",],
["6.4","@gtagamesnl @psyware Good, because I actually do have a bet on Holland winning that I placed before #WorldCup2014 started :)","ChrisJP88",],
],
},
};

var COD = {"name":"COD",
"2014-06":{"neg":[["4.8","Loved the advance tech (smart grenades/boost jumps) in COD: Advanced Warfare. Think the audience found the end a little disarming tho.","jgblankenship",],
["3.86","Someone please explain to me how Call of Duty qualifies as a @XGames event? http://t.co/tCqbgTxHd0","Sharpjabb",],
],
"neutral":[["5","RT @Bondboy7799: Pre-order Call of Duty: Advanced Warfare for #PS4 pre-load now http://t.co/C1ztCMrxf7","DeathlightC7",],
],
"pos":[],
},
"2015-02":{"neg":[["4.69","RT @Treyarch: COD in 2015 confirmed. We look forward to carrying on the conversation...that is, if we haven’t started it already. #InDevelo…","Chris_Holmeren",],
],
"neutral":[["5","RT @VideoGamesFacts: Call of Duty Zombies presentation is happening tomorrow. Treyarch to talk about development process behind popular mod…","CwwKeeler",],
["5","RT @VG247: Zombie mode in #Call of Duty World at War was almost cancelled. http://t.co/rVQMw4isQd http://t.co/hwePrGjRhT","CwwKeeler",],
["5","RT @GoldenboyFTW: Intrigued by what @Treyarch is creating w/ the next Call Of Duty. The studio constantly impresses due in part to guys lik…","V3rmilion_N1nja",],
],
"pos":[],
},
"2014-08":{"neg":[],
"neutral":[["5","RT @AngryJoeShow: Did you know? Robin Williams was a Real Gamer. Loved Portal, COD, Named his daughter Zelda, Had several Warhammer 40k Arm…","cinebst",],
["5","TERMINANDO LA GUERRA EN: Call of Duty: Modern Warfare 3. http://t.co/JTa0ffLgfQ","SEPHIROTHJOSE",],
["5","@G2KGAMES got me a pre-order for COD advanced warfare atlas pro edition. The store is getting better and better #AdvancedWarfare #midnight","zstoots",],
],
"pos":[["5.39","Thanks for 100 subscribers everyone make sure to watch my new video on call of duty zombies it\'s like an hour long so yeah it\'s funny tho 😊","BengamingZ",],
["5.47","TERMINANDO LA GUERRA EN: Call of Duty: Black Ops II. http://t.co/JTa0ffLgfQ","SEPHIROTHJOSE",],
],
},
"2015-01":{"neg":[["1.29","RT @_Xerothor: @xantiaanthem Call of Duty Ghosts is the worst game ever anyway xD","ImPeterBenn",],
["3.94","@TideKit I will put my shoes on the window with the hope the wise kings give me a beta... No,  not COD or game betas,  Tidekit demo now!","t_bogard",],
["3.57","I added a video to a @YouTube playlist http://t.co/wIfGT7P7WP Random Call of Duty Multiplayer #1","XboneHauntsYou",],
["3.37","I added a video to a @YouTube playlist http://t.co/jFYA9p9A7D Random Call Of Duty: Advance Warfare Multiplayer #1","XboneHauntsYou",],
["4.81","Streaming From Xbox360.  || Call Of Duty: Black Ops 2 || XboneHauntsYou: http://t.co/HyoB7s7W2A","XboneHauntsYou",],
["3.88","Random Call Of Duty: Advance Warfare Multiplayer …: http://t.co/uRkJVa0bqr","XboneHauntsYou",],
["3.65","@Treyarch I\'ve been patiently waiting on you to come back. I\'m actually excited for Call of Duty once again.","zstoots",],
["4.09","@InfinityWard Any chance of some older call of duty games making it to next-gen consoles?","zstoots",],
],
"neutral":[["5","27-29 of March COD CHAMPIONSHIP this days @OpTicGaming won im secure #GreenWall @SHGames","Rodri_MDR",],
["5","@StunnerGaming Could they classified for the COD championship???","Rodri_MDR",],
["5","Im nervous for start to seen this #GreenWall @SHGames @OpTicGaming  Official 2015 Call of Duty® Championship Trailer https://t.co/EtU5ncw3Tf","Rodri_MDR",],
["5","RT @CallofDuty: MARCH 27-29th: The 2015 Call of Duty Championship presented by @Xbox is coming. http://t.co/g0K7Dh16aHMore info: http://t…","Rodri_MDR",],
["5","RT @eSportsCOD: Congratulations to @OpTicGaming, your #UMGOrlando25k CHAMPIONS!","Rodri_MDR",],
["5","There\'s call of duty online and now borderlands online.","CwwKeeler",],
["5","Random Call Of Duty: Advance Warfare Multiplayer #1: http://t.co/jFYA9p9A7D via @YouTube","XboneHauntsYou",],
["5","Random Call of Duty Multiplayer #1: http://t.co/wIfGT7P7WP via @YouTube","XboneHauntsYou",],
],
"pos":[["6.59","CALL OF DUTY: Advanced Warfare (Elders React: Gam…: http://t.co/13cLWimODW @JamesDrenning @BrittMcCroskey","_SweetSurrender",],
["6.41","I liked a @YouTube video http://t.co/IFj7I7jxyV Official Call of Duty®: Advanced Warfare – Exo Zombies Havoc Trailer","Daftpedro",],
["6.43","I liked a @YouTube video http://t.co/xYIY1vntIA Official Call of Duty®: Advanced Warfare - Havoc DLC Pack Preview","Daftpedro",],
["7.23","Loving playing #CODAW #ExoZombies as @rosemcgowan. #oosh. 💚","GrahamAllsop87",],
["5.43","RT @AnonymousUK2015: Here\'s the reveal poster for Call Of Duty: World At War 2. We\'ve added our watermark so it doesn\'t get copied. RT http…","pirussas98",],
],
},
"2014-12":{"neg":[["3.08","RT @caraellison: I still can\'t get over that GTA V isn\'t on sale in Australian Target but Call of Duty toys for 10 yr olds are http://t.co/…","JaySevenZero",],
],
"neutral":[["5","@I_AM_WILDCAT How do you get COD prop hunt?","Frost_Wolf61",],
["5","Go accept my 1v1 match on the Xbox 360 COD: Black Ops 2 arena on UMGO @ 04:30 pm CST http://t.co/Ca4A556mYL via @UMGOnIine","MLG_Sperks",],
["5","RT @beachheadstudio: The first official Call of Duty: Advanced Warfare Clan Wars event begins Dec. 5th! For prizing info and more, see http…","MasterMarinara",],
],
"pos":[["6.41","I liked a @YouTube video http://t.co/kVQWgq31rK Official Call of Duty®: Advanced Warfare - Exo Zombies Teaser Trailer","Daftpedro",],
["5.03","RT @CODeSportspedia: For all you early morning risers: Here is today\'s @MLG AW Pro League match schedule! http://t.co/c2VDawYXJ1 http://t.c…","MceowenReid",],
["6.94","RT @AnonymousUK2015: RT if you want us to work on Activision\'s servers for Destiny and Call of Duty.#AnonymousProtection","MLG_Sperks",],
["6.78","I liked a @YouTube video from @boosterbusters http://t.co/snj4CS58VU THE BIGGEST CHEATING CLAN in Call of Duty HISTORY","OtherKrab",],
["6.78","TERMINANDO LA GUERRA EN: Call of Duty: Modern Warfare 2. http://t.co/8yS7f01SaH","SEPHIROTHJOSE",],
],
},
"2014-04":{"neg":[],
"neutral":[["5","New Zombocalypse clan looking for members. #CODGhosts #CallOfDutyGhosts","NewlyDeadEd",],
["5","RT @h101: Predator will appear in the new Call of Duty #CODGhosts #Devastation DLC. http://t.co/i1VoRNKxjc http://t.co/GLIGZHFAow","NewlyDeadEd",],
["5","Zombocalypse clan looking for non pro players to join. Apply via #CODGhosts app #callofduty #ghostsclan","NewlyDeadEd",],
["5","@JaredDudley619 watch yourself man : COD http://t.co/0UmTOQc4XU TF http://t.co/HUWitjymba","SteoAA",],
],
"pos":[["6.25","RT @DreadCentral: The Predator Confirmed for New Call of Duty: Ghosts Devastation DLC http://t.co/MphwdJTIjq #horror","NewlyDeadEd",],
],
},
"2014-10":{"neg":[],
"neutral":[["5","Call of Duty: Advanced Warfare Elite Gear , IGN: http://t.co/ZQ9xliNQLp via @YouTube","BengamingZ",],
["5","Enter #OhMyCoD Ultimate Giveaway w/ @KontrolFreek for a chance to win a ton of Call of Duty: Advanced Warfare prizes! http://t.co/fCCjitnjIj","DeanBoy15",],
["5","Internet + Kraken Headphones + Dubtep music + Call of Duty Advance  Warfare  + Snacks ... Bored time destroyed :)","KobeeMalay",],
["5","@AbeyCOD Okey","PabloPana14",],
["5","Enter #OhMyCoD Ultimate Giveaway w/ @KontrolFreek for a chance to win a ton of Call of Duty: Advanced Warfare prizes! http://t.co/bDkaA2T3wR","pirussas98",],
["5","TERMINANDO LA GUERRA EN: Call of Duty: Ghosts. http://t.co/8yS7f01SaH","SEPHIROTHJOSE",],
],
"pos":[["7.6","I hope I win! Thanks @iEliteShot #FriendlyCODFanboy #EliteSquad #KontrolFreekGiveawayhttp://t.co/0APeQ9IXhh","DeanBoy15",],
["8.22","Win awesome prizes like Call of Duty: Advanced Warfare or an Xbox One Console!  http://t.co/lSnlN1Cuj6","SlimyGibbon",],
],
},
"2014-11":{"neg":[["4.49","@BriaKelly what level and/or prestige are you since you are 8 hours in on COD ?","_SweetSurrender",],
["3.64","COD Ghosts made me give up on that series. This is that all over again with AC. Next year I\'m sure it\'ll be Mass Effect that gets ruined.","joeldawson83",],
["3.59","RT @pewdiepie: BRUH I WISH I COULD BRUH SOME NEW COD ADVANCED WARBRUH WITH MY BRUH SO HE CAN STROKE MY BRUHOLE BRUH BRUH BRUH BRUH BRUH BRU…","pirussas98",],
["2.57","@ATVIAssist I\'m having another issue. It\'s showing me no option to start a discussion on the call of duty forums. Ive tried several browsers","MasterMarinara",],
["2.66","@Vezioking &lt;3 i can\'t play COD at 2:00 AM :S","thePAN1C",],
],
"neutral":[["5","Best COD AW Class Setup: http://t.co/IIf6yfF3OG via @YouTube","BengamingZ",],
["5","Call of Duty: Advanced Warfare Supply Drop Openings Ep1: http://t.co/JOUb7XReqV via @YouTube","BengamingZ",],
["5","Call Of Duty: Advanced Warfare Unboxing &amp; Gameplay: http://t.co/XcsUnMZNep via @YouTube","BengamingZ",],
["5","And all of it decides to work when it wants not when you ask it to. Never have I played a game so broken and rushed. This years COD Ghosts.","joeldawson83",],
["5","Call of Duty AW - Road to 15th Prestige - Gameplay ITA HD: http://t.co/SNQctyjTuF via @YouTube","thePAN1C",],
["5","RT @xboxuk: Happy first anniversary #XboxOne!Retweet for your chance to win a Call of Duty: Advanced Warfare Xbox One console! http://t.c…","thewmatt",],
],
"pos":[["5.7","Check out my broadcast from my PlayStation®4! #PS4live (Call of Duty®: Advanced Warfare)  live at http://t.co/4TucIKzlDJ","_SweetSurrender",],
["5.7","Check out my broadcast from my PlayStation®4! #PS4live (Call of Duty®: Advanced Warfare)  live at http://t.co/4TucIKzlDJ","_SweetSurrender",],
["5.64","#CODAdvancedWarfare multiplayer is the most fun I had on a multiplayer for COD ever","DoubleRM3",],
],
},
"2014-01":{"neg":[],
"neutral":[["5","Played Call of Duty: Ghosts (PC) in the last 24 hours. http://t.co/h1bmShlYu8","Marionchaan",],
["5","Played Call of Duty: Ghosts (PC) in the last 24 hours. http://t.co/h1bmShlYu8","Marionchaan",],
["5","Played Call of Duty: Ghosts (PC) in the last 24 hours. http://t.co/h1bmShlYu8","Marionchaan",],
["5","Played Call of Duty: Ghosts (PC) in the last 24 hours. http://t.co/h1bmShlYu8","Marionchaan",],
],
"pos":[["6.92","I liked a @YouTube video http://t.co/mPpFAuKXP5 GTA 5 Online: DNS CODES WORKING AFTER HOTFIX 1.09!!!","BengamingZ",],
["5.01","I\'m now ranked Experienced (top 60%) in Call of Duty: Ghosts on Raptr! http://t.co/v4vXmJ3fLY","Marionchaan",],
],
},
"2014-02":{"neg":[],
"neutral":[["5","The new call of duty needs a release on this baby! http://t.co/isiP4NGTV0","vectrexfan",],
],
"pos":[],
},
"2014-05":{"neg":[["3.71","Today I remembered why I stopped playing Call of Duty: Ghosts","WillBreidenbach",],
],
"neutral":[],
"pos":[["5.25","Today I started playing Call of Duty: Ghosts","WillBreidenbach",],
],
},
"2014-09":{"neg":[["4.21","@augustgirl515 She\'s probably talking proper nerds that know about games (like you &amp; me). you\'re not a gamer if you\'ve just played COD/Halo.","youreviltwinLP",],
],
"neutral":[],
"pos":[],
},
"2014-07":{"neg":[],
"neutral":[],
"pos":[["6.08","RT @MoneyShotMatt: Ace Sovereign SND (Call of Duty: Ghosts Gameplay) check it out @MceowenReid @bmceowen2 @SmitingFatty @Thecrushsniper  ht…","MceowenReid",],
],
},
};

var TK = {"name":"2K15",
"2014-09":{"neg":[],
"neutral":[["5","RT @NBA2K: We are GOLD. October 7th, preorder http://t.co/lQCAQSZIs9 #NBA2K15 http://t.co/Q8LKo5xKW9","papernut",],
],
"pos":[["5.54","just saw the #WWE2K15 gameplay trailer now im excited and cant wait for it looks awesome @WWEgames @2K #PS4","DoubleRM3",],
["6.02","WWE 2K15 First Official Gameplay Trailer. Ok, now I\'m excited :) http://t.co/dazF4GJIxE","ShinnRyan",],
],
},
"2014-08":{"neg":[["4.43","@WWEgames how about this feud in #WWE2K15 showcase @VivaDelRio vs @CodyBarbierri","DoubleRM3",],
],
"neutral":[["5","RT @IGN: #WWE2K15 details revealed! http://t.co/fRbNg7qIqt http://t.co/Ic1LdXC92l","ShinnRyan",],
["5","@youngced7 @EASPORTSNBA @seanobs Everybody Saw #NBA2K15 leaked! Now it\'s time for #Nbalive15 to drop the Bomb!","SteoAA",],
],
"pos":[["7.71","the entrances for @RandyOrton and @Goldust for #WWE2K15 is awesome cant wait for it @WWEgames","DoubleRM3",],
],
},
"2015-01":{"neg":[["2.5","The Bulls are way too good in 2k15 it\'s annoying af","BrantheeeMan",],
["2.14","@realnba2kprobz i swear i missed a shot with GREEN meter! #NBA2K15","OvereagerMan",],
["3.73","RT @ericlikeivory: If you can\'t get it up, you can\'t get it in. #Jameson #boycottgirls2k15","RobFus_",],
],
"neutral":[["5","RT @WWEgames: This is also your LAST DAY to get #WWE2K15 at @amazon at a special price -&gt; http://t.co/kZjsoLXx7J","trevorosz",],
["5","RT @WWEgames: Grab your copy of #WWE2K15 at @Amazon at a special price &amp; begin your @WWE journey from zero to WrestleMania hero! -&gt; http://…","trevorosz",],
],
"pos":[["8.01","@_CaRtOoNz I was playing/simming King of the Ring on #Wwe2k15 and your character became the King of the Ring that\'s awesome ;)","RageKage5000",],
["6.46","Mmo\'s, rp writing and squeeing over handsome men are what will keep me sane 2k15","Ivaloinen",],
],
},
"2014-12":{"neg":[["4.73","If #NBA2K15 have an update that fixes player models why cant @WWEgames do that with #WWE2K15 with character models","DoubleRM3",],
],
"neutral":[],
"pos":[["5.28","RT @Ashii_san: Hyped for #TokyoGhoul Root A that\'s coming out in #2k15! http://t.co/DaPNrZqrVu","SlimyGibbon",],
],
},
"2014-10":{"neg":[["3.03","All my time have been going into #MyNBA2K15 and #WWESuperCard im so addicted to both of them its unreal","DoubleRM3",],
["3.96","@Ronnie2K i talked to jackson ellis and played for a whole season and still no shoe deal??? #NBA2K15","DoubleRM3",],
["3.02","I cant wait for #WWE2K15 for #PS4 next november needs to hurry up already @WWEgames @2K","DoubleRM3",],
["3.17","Wow really @2K playing #MyTeam and it drops me from the servers and i was up by 3 and it says i lose #NBA2K15","DoubleRM3",],
["3.09","These damn servers keep kicking me off MY Team on #NBA2K15 @2K @NBA2K","DoubleRM3",],
["2.63","I hate how the servers kick me out and i still uses up my contracts #MYTEAM #NBA2K15","DoubleRM3",],
["2.08","Love #NBA2K15 but the music suck so bad bad ideanto have pharrell curated the music lucky u can turn off music @NBA2K @2K","DoubleRM3",],
["3.31","@2KSupport pleaseeee help me! i\'m always offline on #NBA2k15 ps4!!! my internet is working fine and my psn Too. ticket n : #799314","SteoAA",],
["3.0","@2KSupport i can\'t play Myteam on Nba2k15. everytime i select it the game freeze on a black screen and i need to close and reopen the game.","SteoAA",],
["2.46","@2KSupport @SteoAA can\'t play Myteam on #NBA2K15 always give me this Balck Screen and i can\'t do anything","SteoAA",],
],
"neutral":[["5","#WhatMakesMeHappy the midnight release of #WWE2K15 and waiting for #WWE2K15 PS4 as well","DoubleRM3",],
["5","2K is releasing a patch for #NBA2K15 home it fixes the servers for online so delayed on shooting and defense","DoubleRM3",],
["5","@Ronnie2K when will we get sum locker room codes for #NBA2K15","DoubleRM3",],
["5","@2K should give u ur contract back if ur oppenent quits on u in the game so u wont waste them #MYTeam #NBA2K15","DoubleRM3",],
],
"pos":[["5.76","#twitch at midnight http://t.co/lVnlSmtPj3. What do you what to see played? #indie #hearthstone #borderlands #NBA2K15","APhenomenal",],
["6.36","Man everyone and they momma have the ultra rare finals edition of danny green, tony parker, and boris diaw its funny #MyNBA2K15","DoubleRM3",],
["5.55","What i finally unlocked on #MyNBA2K15 mobile app #MJ #GOAT http://t.co/aHaYRZoWJ2","DoubleRM3",],
["5.47","Of course ppl pick the cavs in online quick match no skill #NBA2K15","DoubleRM3",],
["6.56","Love the pre game show with @SHAQ and @TurnerSportsEJ its so great. would be awrsome if they had a half time show as well #NBA2K15","DoubleRM3",],
["5.03","#NBA2K15 finally comes out this coming tuesday super excited cant wait @NBA2K @2K #PS4","DoubleRM3",],
["5.2","@2KSupport if i create a New user on my ps4 and i play Nba2k15 with this all goes fine! That\'s absurd! is my original 2k profile corrupt??","SteoAA",],
],
},
"2014-11":{"neg":[["2.84","got #WWE2K15 on PS4 great graphics but really they couldn fix ambrose and rollins singles attire and no superstar threads but weak roster","DoubleRM3",],
["4.48","@2KSupport my myteam keeps freezing after i complete a challenge and i reseted it and it still happens after a challenge #NBA2K15 #MYTEAM","DoubleRM3",],
],
"neutral":[["5","so @WWEgames did not put in the current entrances of @WWERollins and @TheDeanAmbrose in #WWE2K15 for next gen now im disappointed","DoubleRM3",],
["5","Im wonderin when will 2K release some locker codes #NBA2K15 #PS4","DoubleRM3",],
],
"pos":[["5.76","#MyTeam #NBA2K15 my squad is a force nature http://t.co/Va5eK4tyI4","DoubleRM3",],
["5.21","and  just realized in 2 weeks #WWE2K15 comes out for #PS4 and #XboxOne im excited for it","DoubleRM3",],
["5.48","I liked a @YouTube video from @smacknetwork http://t.co/CJdtZcMScO WWE 2K15: Randy Orton Entrance Comparison (PS4/PS3)","videodiscthings",],
],
},
"2015-02":{"neg":[],
"neutral":[["5","RT @WWEgames: No time like the present! Get #WWE2K15 at a special price at @GameStop -&gt; http://t.co/b7WWDchJh6","trevorosz",],
],
"pos":[["5.1","Oh hey guys, the \"One More Match\" DLC for #WWE2K15 is out today, you should check it out. I will be playing it soonish.","trevorosz",],
],
},
"2014-07":{"neg":[["4.29","@WWEgames can there be a @Sting cover for #WWE2K15 I don\'t want the cena one #WWE #RAW","DoubleRM3",],
],
"neutral":[["5","RT @WWEUniverse: Best looking orchestra EVER!! @STING comes to #WWE2K15!! Pre-order today. http://t.co/3Dw5WEYSah  @WWEGames http://t.co…","ECHODIVISION5",],
["5","Sting Debuts in \'WWE 2K15\': http://t.co/DW3bzQIExO via @YouTube","videodiscthings",],
],
"pos":[],
},
};

var Halo = {"name":"Halo",
"2014-11":{"neg":[["3.58","@Halo been watching through the whole tournament so far, clock is almost 5 am but who cares, WE BACK!","deathbox_",],
["3.83","Hard time deciding what team to root for in the @Halo Invitational, so it\'ll be #OpticGaming#TheAgency#StK gl y\'all! http://t.co/8erJw0SsyV","deathbox_",],
["4.48","RT @TheJoeyWay: Bungie watching 343 Industries fail with this Halo launch like #HaloMCC http://t.co/uiStSw4GP0","JHogan1994",],
["2.29","Halo is the only thing keeping me sane","TheAmazinGeorge",],
["3.88","Only one and a half pages in and I am having trouble fighting the urge to read a comic or play some Halo","TheAmazinGeorge",],
["3.33","Whenever I think about The Grapist, I have to watch it… Then I end up watching the Halo 2 Gangster Rap… Those used to be the funniest videos","TheAmazinGeorge",],
],
"neutral":[["5","Searched in H2C, got a game in H2A? @Halo @Brav","deathbox_",],
["5","RT @PlutonForEver: 2 days til #Halo TMCC invitational. http://t.co/tqm5kIFFdr RT for a chance to win his and hers keychains http://t.co/Ky4…","deathbox_",],
["5","RT @PlutonForEver: We just released Halo novel,Broken Circle.RT for chance to win the book and snazzy lanyard. 6 sleeps til #Halofest http:…","deathbox_",],
["5","@markiplier #CyndagoLA What else do you plan to play besides Halo and Five Nights at Freddy\'s","grenier1of3",],
["5","Where the fuck is the post man with halo? Wanna play it for god sake","JHogan1994",],
["5","RT @xboxuk: Become a part of #Halo history!Retweet for your chance to attend the exclusive Halo launch party! #HaloNation https://t.co/…","richardjpease",],
["5","HALO MASTER CHIEF COLLECTION IS LIVE","TheAmazinGeorge",],
],
"pos":[["6.15","I liked a @YouTube video from @djy1991 http://t.co/N0GZxj6ouZ Halo: Halos in Space","Beast_Man101",],
["5.88","started listening to @theRealShooKon3 and became better. I\'M ON A HUNDO #XboxOne#Halo https://t.co/nfTDU6span","deathbox_",],
["5.61","RT @xSaLoT: How strong is the halo community? die hard halo fan #RT this and show me your love for halo!! followed as a bonus #HaloWall","deathbox_",],
["8.05","RT @ESL: Giving away awesome @ASTROGaming &amp; @Halo stuff to celebrate #HaloFest &amp; #Halo #MCC Launch! RT! http://t.co/xHkkWVjbrQ http://t.co/…","deathbox_",],
["6.97","@Halo @ESL watching Halo again feels so good, bringing back the nostalgia. #halo #halofest #weback","deathbox_",],
["5.41","@suddoth1 @Halo @Twitch is that in 3 or 4 hours?","deathbox_",],
["5.38","Plenty of gaming between Halo MCC and GTA V on Xbox One in next few weeks. Can\'t wait. #whatsoldisnewagain","EdsHead",],
["5.77","I liked a @YouTube video http://t.co/x9bWnUYDGx Advanced Warfare vs. Halo 5: Guardians (PARODY Video of Multiplayer Gameplay)","OtherKrab",],
],
},
"2015-02":{"neg":[["3.67","@Halo please, before you put out new playlists, put in ranks in the already existing ones. No fun playing the game and not seeing progress","deathbox_",],
["3.72","@Halo and wouldn\'t it be better if you stopped putting out new playlists and also focused om MM issues, less playlists to handle?","deathbox_",],
["4.25","RT @yessimmixed__: @SiRJO5HALOT got me weak AF with all these RT 😭😭😂😂😩😩","SiRJO5HALOT",],
["3.97","RT @yessimmixed__: Josh text me talking bout football 😭😭😂 right he forgot im the basketball bestfriend not football 😭😂@SiRJO5HALOT","SiRJO5HALOT",],
["4.82","@TheOxfordMail it\'s huuuuge! Hey @VirtualAstro what\'s causing the halo round the moon?","swissyellow",],
["4.1","RT @Xtreme_Gaming: Guys apologies for short stream seems @halo still is not fixed - getting so far on legendary co-op for it to crash makes…","V3rmilion_N1nja",],
["3.62","RT @HaloCE: @yosp @eurogamer @Kotaku @PlayStation A depressing thread on Sony\'s horrendous customer service: http://t.co/BujhjMVbJ5 #basica…","Xexyzx",],
],
"neutral":[["5","RT @gameinformer: Improving The Master Chief Collection Experience Remains ‘Top Priority’ For Halo Team - http://t.co/1aTQsu0mdD http://t.c…","bilbothebrave",],
["5","I know 🙊 “@cameronxinglis: @SiRJO5HALOT is the best for what he just did 😂😁”","SiRJO5HALOT",],
["5","Ask around. I run NC. “@LurchBrasi_: Bro you RT that tweet meaning you tryna get ya legacy killed in this 2k @SiRJO5HALOT”","SiRJO5HALOT",],
],
"pos":[["5.89","RT @NiceGuyJason: Aye got top 5 with of bunch of randoms at NJ Halo","Goshi_US",],
["6.41","RT @DOMA4YoMAMA: Yo @SiRJO5HALOT retweeting the funniest shit about the game 😂","SiRJO5HALOT",],
["6.74","RT @TheOxfordMail: Has anyone else spotted the beautiful halo around the moon tonight in Oxford? Tweet us your pics and we\'ll use what we c…","swissyellow",],
["7.37","RT @TimBurgess: Hexagonal ice crystals in the atmosphere create this amazing 22° halo around the moon -https://t.co/HwBl6hMcjK @SimonParkin…","swissyellow",],
],
},
"2014-08":{"neg":[["2.49","RT @Soloxboxone: @XboxP3 @MrPhilHarrison @AceyBongos @majornelson Halo 2 A w/o Castilian dub &amp; sub, Xbox Feedback really worthless https://…","Alex_CG17",],
],
"neutral":[],
"pos":[],
},
"2015-01":{"neg":[["4.29","RT @VG247: Halo: The Master Chief Disaster -  Xbox One’s Xmas game is still a turkey, says @RichStanton http://t.co/Tv5L390flq http://t.co/…","Alpha118",],
["4.49","@Grindlethorpe @Halo a game that cut out armour customisation in favour of the \"Gungoose\"? Surely not...","Alpha118",],
["2.65","It\'s down right ridiculous now. Bungie did well to make Halo what it is, and seeing it get shat on slowly is just sad","Alpha118",],
["3.38","RT @TheHaloArray: Please RT to save a life. Don\'t blindly pre-order a game. Fool me once shame on you, fool me twice.... http://t.co/UvKwTS…","deathbox_",],
["3.1","RT @YahooAnswersTXT: My girlfriend beat me at Halo 3. Should I dump her?","LoopyCCoopy",],
["3.22","@RockmanHalo don\'t make me smack you","MewlesVerne",],
],
"neutral":[["5","However Pegasus is the most \"Halo\" out of the 2 maps and their variants that have come up in the Beta","Alpha118",],
["5","@OXMUK Halo Wars","Alpha118",],
["5","@Grindlethorpe @Halo quick, someone replace the thin veil of lies before we notice anymore bullshit. Like the game still being broken","Alpha118",],
["5","343 have done an amazing job announcing 2 new Halo 5 beta maps which are actually the same 2 from last week in disguise","Alpha118",],
["5","And whilst I get the whole Spartan / Halo link actually using the name Spartan is pretty aggrandizing for a web browser.","Cha1rman_Meow",],
["5","RT @TeamBeyondnet: [GIVEAWAY] Halo Championship Series T-Shirt RULES: RT &amp; Follow us to win! http://t.co/ZMN7dryrRh","deathbox_",],
["5","Check out the Halo pro @Elumnite, he\'s streaming right now! http://t.co/pGu2XSjxHP 👌","deathbox_",],
["5","@ScottGandhi @HiRezAPC from another Halo brotha to anotha yo","deathbox_",],
["5","@Halo searching in Halo 3 playlist http://t.co/2J9eVbb4KL","deathbox_",],
["5","@C9Ninja @C9Fearitself @C9Hysteria @C9Victory Go get em\' boys! #halo #halomcc #UGC20K","deathbox_",],
["5","@RockmanHalo you get three days in the hugbox","MewlesVerne",],
["5","@RockmanHalo RIIIIIIGHT","MewlesVerne",],
["5","@RockmanHalo confess and repent, my friend","MewlesVerne",],
["5","People, @RockmanHalo knows more then you will ever care to find out.","MewlesVerne",],
["5","@RockmanHalo GLOBAL","MewlesVerne",],
["5","RT @yessimmixed__: To hear @SiRJO5HALOT talk about @cameronxinglis and see the smile he has every time he says her name warms my heart. 😍😍😍…","SiRJO5HALOT",],
],
"pos":[["5.13","Last week of the Halo 5 Multiplayer and another a new map, which could be summed up as a featureless map that you\'d see in forge","Alpha118",],
["7.13","@Grindlethorpe ah yes, it\'s fantastic. It\'s also great that the Covenant ship map is essentially Halo 2\'s Midship map","Alpha118",],
["6.0","@Taijavuh @EGL @HaloForumEU oh okey, thanks!","deathbox_",],
["5.2","RT @Thrust__: Playing @Halo wireless on my schools wifi connection got me like http://t.co/Etc2pUadxH","deathbox_",],
["7.77","RT @DreBeller: Great hoops session with @SiRJO5HALOT","SiRJO5HALOT",],
["7.49","RT @CoachPerkins: @SiRJO5HALOT @coach_mac4 No Josh, it was my honor to coach you.  A true role model for other players to emulate","SiRJO5HALOT",],
],
},
"2014-12":{"neg":[["4.97","@Grindlethorpe @Halo only if you make me pancakes first","Alpha118",],
["4.73","🔪🙈💩 I\'m F\'ing excited for this game. #Halo5 #Xbox #Gaming #Videogames http://t.co/yrtiSik5PV","Daftpedro",],
["4.22","🙌👊🔫🔪🎮👾 #Halo5 Multiplayer Beta!  Only on #Xbox One. http://t.co/z7MtvWke46","Daftpedro",],
["3.75","Is it worth getting #CoDAW ? Thinking of getting it for the lols, might get hooked, maybe not, need something to play while #halo is broken.","deathbox_",],
["4.6","Seeing all the #Halo5 feedbacks are making me happy. If 343i actually listens to what we have to say this game could actually be pretty good","deathbox_",],
["3.93","In which I have a formidable backlog of games. Halo, GTA V, Far Cry 4, Super Smash Bros., Little Big Planet 3....yeah, I\'m good.","EdsHead",],
["4.35","RT @Briskster: @Briskster it comes with AW or Halo!","MLG_Sperks",],
["2.71","@Xbox This Halo crap is getting old. I sure hope you have more to offer in 2015 than just Halo.....","papernut",],
],
"neutral":[["5","@Grindlethorpe what happened to romantic evening of Halo 5 and Pancakes? ;-;","Alpha118",],
["5","\"now nobody plays shooters the way they used to play them before Halo \'cause nobody wants to.\"This why I can\'t enjoy pad shooters. #halo","BludBank",],
["5","Playing Warlord and not having atleast a decent team is a living nightmare, ugh. #halo#halomcc","deathbox_",],
["5","@Halo @Brav have been trying to find a match all day, keeps saying \"restarting search\" or \"no connection\"","deathbox_",],
["5","@Halo when are we getting the exclusive nameplate and avatar in mcc?","deathbox_",],
["5","RT @TeamBeyondnet: [GIVEAWAY] Halo 3 @ASTROGaming #SpeakerTagshttp://t.co/9Wwea27wdARULES: RT &amp; Follow us to Win! http://t.co/PjhwIZpnfV","deathbox_",],
["5","@Halo I had the Spartan Strike avatar just now, but after a game it disappeared :/","deathbox_",],
["5","@PlutonForEver @Halo @Danayoub when is the Nameplate and Avatar coming? This week?","deathbox_",],
["5","@jetsethradio HALO 3 IN HD ON XBOX ONE YESSSSS!!!!!!!!!!!!","jellybean710",],
["5","@Briskster aw over halo","MLG_Sperks",],
["5","I\'m a video game player today because of #Halo. The #MasterChiefCollection is still broken after being out for almost a month. INEXCUSABLE.","PersonalOwn4g3",],
],
"pos":[["5.55","Halo 5 Beta is the best version of MW2 Multiplayer complete with spawning on top of enemies. Also black screens https://t.co/EillsvxO1t","Alpha118",],
["5.37","It is a far stretch from the Halo 4 travesty, which is good, maybe even a bit more Reach-esque","Alpha118",],
["5.11","@Tom_the_Hobbit no worries. Glad you like the stuff. Thank you very much for my Totoro and Halo book, looking forward to getting stuck in","Alpha118",],
["5.8","@Grindlethorpe @Joshua__Evans we playing Halo or what yo?!","Alpha118",],
["5.67","RT @ASTROGaming: Start your #NewYear right w/ the #ASTROfamily Pros at #UGC20K &amp; #UMGOrlando! LIVE on 1/2/15.#Halo #AdvancedWarfare http:…","Angel_Meraz",],
["5.15","Even though I got real shitty connection right now, I still keep blaining the enemies in #halo3, ahh good times. #halo #halomcc","deathbox_",],
["7.11","@GoldenboyFTW @Halo tbh, it\'s actually pretty stable, minor fixes and changes and the game is gonna be real good!","deathbox_",],
["5.63","Man, watching @Zola85 \'s Halo Retrospect Doc. gets me so nostalgic. Thinking back on all the good times I\'ve had, brings a tear. Gj Zola. 👍","deathbox_",],
["6.09","Tomorrow. #halo#halo5 http://t.co/G493s89iI5","deathbox_",],
["6.76","@Zola85 It sure does work, really different from other Halos imo, but it\'s looking good. If 343 listens to the community it\'ll be good!","deathbox_",],
["5.6","@JtoAtoKtoE @GoldGloveTV It has the photoshop halo... it\'s photoshopped","Frost_Wolf61",],
["6.34","#omg an hour of #Halo 5 multiplayer gameplay http://t.co/Vw6WRPyc0V #awesome #xbox #one","Marthyn",],
],
},
"2014-10":{"neg":[],
"neutral":[["5","RT @GlenSchofield: 6 days! AdamParis, @AaronHalon, Robert Taylor https://t.co/cXcDuPpL9q","pirussas98",],
],
"pos":[["5.15","@KinsZilla @MetalJesusRocks Nice! Love that Halo one. I also have the Tomb Raider &amp; Halo 3 ODST sealed packed away. http://t.co/z7MIHt0skU","EdsHead",],
],
},
"2014-06":{"neg":[],
"neutral":[["5","RT @VirtuaMe: #E3Halo: The Master Chief Collection#XboxOne 1080p 60fps http://t.co/blaWsYBwXc","DeathlightC7",],
],
"pos":[["5.36","RT @GameZoneOnline: Did Microsoft just tease Halo 2: Anniversary Edition? http://t.co/Iisaei12hB","DeathlightC7",],
],
},
"2014-09":{"neg":[["4.21","@augustgirl515 She\'s probably talking proper nerds that know about games (like you &amp; me). you\'re not a gamer if you\'ve just played COD/Halo.","youreviltwinLP",],
],
"neutral":[["5","RT @GAMEdigital: #GAMEDestiny - Master (Chief) your Destiny. Xbox One + Destiny Vanguard + Halo Master Chief Collection for £349.99! http:/…","JHogan1994",],
],
"pos":[["6.13","@Srob93_Music if your a fan of halo you\'ll like it plays just like it. Just because it\'s made by the original creators of halo.","JetLife091",],
["6.13","@MrJayBanc if your a fan of halo you\'ll like it plays just like it. Just because it\'s made by the original creators of halo.","JetLife091",],
],
},
};

var Minecraft = {"name":"Minecraft",
"2014-06":{"neg":[["3.96","Just got done recording the walls on minecraft and I freakin won I\'m the master of the walls","freakypancake",],
],
"neutral":[],
"pos":[["5.7","RT @Gam3Newz: Minecraft Console Sales Surpass PC Version - http://t.co/u7OY9ubZdg - ign","DeathlightC7",],
["5.87","RT @LatestPS4: Minecraft on PS4 to feature touchpad support; PS3 upgrade discount confirmed http://t.co/AInfWVj3vU”","DeathlightC7",],
["5.67","Just recorded episode one  of course minecraft a epic parkour map","freakypancake",],
["6.46","Woooooo minecraft feed the beast season finale was awesome it so epic","freakypancake",],
["5.21","If you could rename one item in minecraft which item would it be and what would you rename it to","freakypancake",],
],
},
"2014-09":{"neg":[["4.93","Minecraft x1 edition - my old roman town: http://t.co/3YyA4N8YVp","JHogan1994",],
],
"neutral":[["5","Subscriber Floor Minecraft PS4: http://t.co/wFeIN5fT9u via @YouTube","BengamingZ",],
["5","Ik vind een @YouTube-video van @bdoubleo100 leuk: http://t.co/XfQlIs5LDa Minecraft :: What No Man Has Done Before! :: Attack of the","OtherKrab",],
["5","RT @Kotaku: It\'s a fight to the death between Mario and Minecraft Steve: http://t.co/0jibfbPdLT http://t.co/0qQrFDpfBK","OtherKrab",],
],
"pos":[["5.35","I liked a @YouTube video http://t.co/7McXMQxgA5 Minecraft FTB Blood and Bones 23 - NEW ARMOR OF FABULOUS(Minecraft Mod Survival FTB)","Beast_Man101",],
["5.34","I liked a @YouTube video from @jeromeasf http://t.co/FpqXT1CUbq Minecraft CHICK MAGNET w/ SkyDoesMinecraft, OkwardIndustries and","Beast_Man101",],
["6.2","RT @jon_cham: Illustration why MS bought Mojang.Me: Minecraft got bought.10yo: awesome. How much?Me: $2.5B10yo: wow. By who?Me: Micros…","GarvielL0ken",],
["6.08","I liked a @YouTube video from @kurtjmac http://t.co/0oPrN5KHE9 Minecraft Far Lands or Bust - #405 - Different Octave","OtherKrab",],
["5.47","I liked a @YouTube video from @zisteau http://t.co/w8kZXG979M Minecraft :: Mindcrack No. 15 - \"Messy Noteblock Array\"","OtherKrab",],
],
},
"2014-08":{"neg":[["4.92","I liked a @YouTube video from @skydoesminecraf http://t.co/9r5unzfuMa Minecraft Battle Dome : WHY NO DIAMONDS?!","Beast_Man101",],
],
"neutral":[["5","RT @SaundersJemma: “@guardian: Minecraft add-on LearnToMod aims to teach children coding skills http://t.co/UOapBvIgqk via @guardian” @Newl…","NewlyDeadEd",],
],
"pos":[["5.99","I liked a @YouTube video from @skydoesminecraf http://t.co/qvvdHiGi85 Minecraft Animated Short : MOST AWKWARD MOMENT EVER!","Beast_Man101",],
["5.3","I liked a @YouTube video from @skydoesminecraf http://t.co/cujZ5eXOPy Minecraft Animated Short : HOW TO EMBARRASS DEADLOX!","Beast_Man101",],
["5.66","I liked a @YouTube video from @skydoesminecraf http://t.co/R8fzP7yXbF Minecraft Animated Short : DO YOU WANT TO TAKE A DUMP? (Frozen","Beast_Man101",],
["6.35","I liked a @YouTube video http://t.co/y6RzmqWpB2 Minecraft - GROWABLE ORES MODS - NEW WAYS TO GROW ORES","Beast_Man101",],
["5.83","I liked a @YouTube video from @m1stknight http://t.co/qIGNthSiif Minecraft Survival Series | How to build a Chinese house","Beast_Man101",],
],
},
"2015-01":{"neg":[["2.29","@Bopogamel it\'s would be nice if you guys didn\'t make minecraft boring. Add some more ores or even vehicles to the game! PLEASE!!!!!","Frost_Wolf61",],
["3.04","RT @zachbraff: I don\'t know what this is, but apparently it\'s a thing. #minecraft http://t.co/dgC04xi7Ay","jova7587",],
],
"neutral":[["5","@cowfishdreams @Ace_McDunk Sunset Overdrive, Minecraft and then maybe wait for Quantum Break reviews, failing that GTA or Destiny","Alpha118",],
["5","RT @NickThomas195: This is minecraft art &lt;3 @daveexplosm http://t.co/hqv3tJDZsa","Mak0rz",],
["5","RT @Kotaku: Explore Gondor\'s ancient capital from Lord of the Rings in Minecraft: http://t.co/ujCAVlrp7a http://t.co/hds1oiJ2op","mix_martes86",],
["5","RT @VG247: Someone is attempting to recreate #DarkSouls\' Lordran in Minecraft   http://t.co/v8QcWYGN4s http://t.co/i3Mmj1H1y5","CwwKeeler",],
],
"pos":[["6.44","I liked a @YouTube video http://t.co/29zbGhOc4q Minecraft Mod - WearMC MOD - CHANGE HOW YOU LOOK!!","Beast_Man101",],
["5.17","Made Minecraft cookies for the girls. No cookie cutters means a lot of work for me! http://t.co/lDMG71GhQS","geekonursleeve",],
["5.6","If you own an iPhone or iPad you got to get on Crossy Road. That game is hype incarnate. Plays like Frogger but has the style of minecraft.","joeldawson83",],
["7.51","RT @Kotaku: A group of 125 is building all of Game of Thrones in Minecraft, and it still looks amazing. http://t.co/W3lBCCTr7H http://t.co/…","mix_martes86",],
],
},
"2014-12":{"neg":[["4.85","I liked a @YouTube video from @skydoesminecraf http://t.co/M5PSkQp6Rr Minecraft Mod Showcase : FIVE NIGHTS AT FREDDY\'S 2 MOD!","Beast_Man101",],
["2.99","@pcgamer Great, as if Minecraft wasn\'t shit already... 😒","Frost_Wolf61",],
],
"neutral":[["5","RT @Kotaku: Minecraft\'s creator just bought the most expensive house in Beverly Hills http://t.co/XwVT41iSbt http://t.co/YYtVDqCLli","MuroJulian",],
],
"pos":[["5.66","I liked a @YouTube video from @gizzy14gazza http://t.co/KKfdyNbhvr Minecraft Animation: DO YOU WANNA WATCH SOME GIZZY? (Music Video)","Beast_Man101",],
["5.87","I liked a @YouTube video from @huskymudkipz http://t.co/J6yzT43uqL \"Twerk Tree Returns!!\" Minecraft - SkyFactory 2 Modpack! - EP #1","Beast_Man101",],
["5.62","I liked a @YouTube video from @skydoesminecraf http://t.co/etUnKSEGTt Minecraft Fan Animation : I\'VE GOT EH DEE DEE!","Beast_Man101",],
["6.64","I liked a @YouTube video from @cjggaming http://t.co/PwNMbS9ru8 How to use an XBox 360 Controller for Minecraft [PC]","Beast_Man101",],
["6.07","I liked a @YouTube video http://t.co/alFpp8J5sj Minecraft Modded SkyFactory 20 - EVEN MORE POWER","Beast_Man101",],
],
},
"2014-10":{"neg":[["4.94","I liked a @YouTube video from @markiplier http://t.co/bP3lgdV9Gx Drunk Minecraft #65 | FIVE NIGHTS AT MINECRAFT","Beast_Man101",],
],
"neutral":[["5","Train journeys are no longer boring thanks to Minecraft on PS Vita :D","alexflannagan",],
],
"pos":[["5.65","@GameOverGreggy @agentbizzle @MinecraftIGN wahoo! Can\'t wait to watch","alexflannagan",],
["5.08","I liked a @YouTube video from @skydoesminecraf http://t.co/oXieay4NDZ Minecraft Mini-Game : DO NOT LAUGH 16!","Beast_Man101",],
["5.04","I liked a @YouTube video from @skydoesminecraf http://t.co/mmh2I0B2LR Minecraft Mini-Game : DO NOT LAUGH HALLOWEEN SPECIAL!","Beast_Man101",],
["6.34","I liked a @YouTube video http://t.co/aj6fSTnm1t Minecraft Crash Landing 6 - THE HIGH OVEN","Beast_Man101",],
],
},
"2014-11":{"neg":[["3.98","RT @NetworksManager: He\'s not letting me turn #miner off. #MineCraft #server #hashing at 3k h/s as well https://t.co/ovhGPri4MN #bitcoin ht…","HaasMonty",],
["3.45","@chelseachan a glorified Minecraft. Not my favourite HM by any means.","Musikophilia",],
],
"neutral":[["5","Minecraft | Skyblock Server | Playing With Mods http://t.co/hZY1bNByje via @Twitch","Frost_Wolf61",],
],
"pos":[["6.25","I liked a @YouTube video http://t.co/7p8VlqCm0Y Minecraft Modded SkyFactory 11 - I BELIEVE I CAN FLY","Beast_Man101",],
["5.03","I liked a @YouTube video from @skydoesminecraf http://t.co/gVV704blG5 Minecraft Mini-Game : DO NOT LAUGH 18!","Beast_Man101",],
["6.34","I liked a @YouTube video from @slamacow http://t.co/XBIAiLBlwD Stick By Me - Minecraft Animation - Slamacow","Beast_Man101",],
["5.38","I liked a @YouTube video from @diamondminecart http://t.co/WaucQy9Gsp Minecraft | MOB GUNS MOD! (DanTDM &amp; Trayaurus GUN!) | Mod","Beast_Man101",],
["5.16","I liked a @YouTube video from @skydoesminecraf http://t.co/8cgVoeH7BN Minecraft Animated Short : THE DEPRESSING STORY!","Beast_Man101",],
["5.62","I liked a @YouTube video from @skydoesminecraf http://t.co/eSeXDzz1J5 Minecraft Animated Short : \"IF I COULD SEE YOUR FACE\" A Music","Beast_Man101",],
],
},
"2014-01":{"neg":[],
"neutral":[],
"pos":[["5.7","I liked a @YouTube video from @worldofkeralis http://t.co/rzfihSI1Lf Minecraft: How To Build a Simple Starter House","BengamingZ",],
["6.35","I liked a @YouTube video from @sethbling http://t.co/7psBdtGAFs Cow Proximity Detector Alarm System in Minecraft","BengamingZ",],
],
},
"2014-03":{"neg":[],
"neutral":[],
"pos":[["6.31","I liked a @YouTube video from @worldofkeralis http://t.co/4iQEnREJh6 Minecraft House Tutorial: Suburban House - Part 1","BengamingZ",],
["5.83","I liked a @YouTube video from @bean_on_a_board http://t.co/9NOKtminJ6 Mansion Tutorial - Minecraft PS3/Xbox 360 #2","BengamingZ",],
],
},
"2014-05":{"neg":[],
"neutral":[["5","RT @Kotaku: This guy can play Minecraft with his eyebrows: http://t.co/SlagErVJeF","videodiscthings",],
],
"pos":[],
},
"2015-02":{"neg":[["3.95","RT @tgnTV: Sometimes I wish I could be this creative. #Minecraft http://t.co/ivv0wcHLsa","RookieMC97",],
["4.59","@SilverWolv since a SOLO PLAYER is alone.That kinda applies to Minecraft as well, the logic is pretty neat also","RookieMC97",],
],
"neutral":[["5","A MineCraft Series: Ep1 Kingdom Bank: http://t.co/kWvBO7D2T4 via @YouTube  @vortacvids","GrahamAllsop87",],
["5","Anyone wanna play some MineCraft hunger gamers on the Hive.mc? If so let me know! @kidmarcus4 @MineCraftRTweet","MLG_Sperks",],
["5","People were making fun of her.What\'s wrong with people. She was just another girl who wanted to play Minecraft with Notch,nothing to judge.","RookieMC97",],
],
"pos":[],
},
"2014-07":{"neg":[["4.7","I added a video to a @YouTube playlist http://t.co/jqjxUms4vf Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 4","BengamingZ",],
["4.91","I added a video to a @YouTube playlist http://t.co/ZvkGMk7OW5 Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 3","BengamingZ",],
["4.75","I added a video to a @YouTube playlist http://t.co/Pwe9EpERtZ Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 1","BengamingZ",],
["4.71","I added a video to a @YouTube playlist http://t.co/LbxU7CuYT3 Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 2","BengamingZ",],
],
"neutral":[["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 4: http://t.co/jqjxUms4vf via @YouTube","BengamingZ",],
["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 6: http://t.co/P4ren7UJbu via @YouTube","BengamingZ",],
["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 3: http://t.co/ZvkGMk7OW5 via @YouTube","BengamingZ",],
["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 5: http://t.co/Fl295kekkT via @YouTube","BengamingZ",],
["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 2: http://t.co/LbxU7CuYT3 via @YouTube","BengamingZ",],
["5","Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 1: http://t.co/Pwe9EpERtZ via @YouTube","BengamingZ",],
["5","just played minecraft pocket addition with the new update it is awesome","freakypancake",],
["5","RT @MinecraftIGN: Greg and Brian try to learn water in episode 43 of our Minecraft Let\'s Play http://t.co/v6J4fC6AxV || http://t.co/2qwbfoV…","ShinnRyan",],
],
"pos":[["6.26","I liked a @YouTube video from @bengamingz http://t.co/LbxU7CuYT3 Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 2","BengamingZ",],
["6.24","I liked a @YouTube video from @bengamingz http://t.co/jqjxUms4vf Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 4","BengamingZ",],
["6.29","I liked a @YouTube video from @bengamingz http://t.co/Pwe9EpERtZ Minecraft Survival with BengamingZ &amp; JoshgamingZ Ep 1","BengamingZ",],
["6.11","My nice lil shack in minecraft mobile http://t.co/Oqe2sjX6Oy","freakypancake",],
["6.24","Chilling with ma pups #Minecraft http://t.co/zCZkrpxlhz","freakypancake",],
],
},
};

var AC = {"name":"Assassin's Creed",
"2014-11":{"neg":[["4.37","My dog Angus and I chillen outside my social house lol #assassinscreedunity   #PS4share http://t.co/Kyv81ggdnY","_SweetSurrender",],
["3.03","Man on my assassin the guild I was in shutdown man I was top too dang it","jahxchuggaa",],
["1.6","I guess I have no reason not to start Assassins Creed Unity after all. #blizzardserverqueues #wodexpac","Synessa",],
],
"neutral":[["5","Can no one connect to their friends on Assassins Creed Unity ?? #assassinscreedunity #assassinscreed #playstation4 #ps4","_SweetSurrender",],
["5","RT @Kotaku: Our microtransactions expert spent $100 on Assassin\'s Creed Unity to see what would happen: http://t.co/TLCCFasv4R http://t.co/…","joeldawson83",],
["5","Took the quiz \"What Type of Assassin Are You?\" &amp; got \"Ranged Assassin\". http://t.co/l2eEqWssyL","LeonardoSkylar",],
["5","Assassin\'s Creed 4 Black Flag | The Ultimate Tribute [HD]: http://t.co/i5C9Tqtxp3 via @YouTube","LeonardoSkylar",],
],
"pos":[["5.38","RT @SignedInPodcast: Episode 153: Far Cry 4, Assassin\'s Creed Rogue, CoD Advanced Warfare, This War of Mine, GTA V &amp; MORE! http://t.co/fASl…","evild70",],
["7.58","@emilegauthier @EscoBlades @UbiGabe @assassinscreed @Twitch Hahah awesome!","j0hke",],
["7.31","RT @OMGitsAliA: Giveaway time! @Assassins_UK and I are giving away a Guillotine edition of #ACUnity - RETWEET &amp; follow to win! :D http://t.…","richardjpease",],
["6.59","RT @SamuraiBambi: Videogame music live @DigiExpo #messukeskus #digiexpo #ACIV #EldersScroll #AssassinsCreed http://t.co/nBuGuiDp9T","Quinsonitus",],
["5.73","I won the Technical Difficulties achievement in Assassin\'s Creed: Brotherhood for 10 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
],
},
"2015-02":{"neg":[],
"neutral":[["5","@SocialAssassin2 @bcondotta Paging Golden Tate....","GarthMcKenzie",],
["5","DEFY - Official Live Action Trailer | Assassin\'s Creed 4 Black Flag [UK]: http://t.co/WvFoczbxAt via @YouTube","LeonardoSkylar",],
["5","RT @OXONAssassin: Nintendo could surely sue right? They are stealing this set up from Rainbow Road.","swissyellow",],
["5","@OXONAssassin nope, wrong :-)","swissyellow",],
],
"pos":[["5.36","RT @OXONAssassin: LYNCH!","swissyellow",],
["5.95","I won the Plumber achievement in Assassin\'s Creed: Brotherhood for 25 #TrueAchievement pts - http://t.co/9vfpEgJxEg","Xexyzx",],
],
},
"2014-08":{"neg":[],
"neutral":[["5","RT @gamespot: We break down the Assassin\'s Creed Rogue trailer -- watch now: http://t.co/GzuZy7p7Wn http://t.co/bszhxQmDTd","ShinnRyan",],
],
"pos":[],
},
"2015-01":{"neg":[["4.95","RT @caneandrinse: Got something to say about Assassin\'s Creed III? You\'ve only got until later today if you want it on the podcast!http://…","JaySevenZero",],
["4.99","I won 2 achievements in Assassin\'s Creed: Brotherhood for 48 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["4.99","I won 2 achievements in Assassin\'s Creed: Brotherhood for 48 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
],
"neutral":[["5","@SocialAssassin2 New Air Jordan smell is up there.","GarthMcKenzie",],
["5","The Raid\'s Rama, The Assassin and Machete Guy cast in Star Wars: The Force Awakens!!!??? *FAINTS*","GarthMcKenzie",],
["5","@SocialAssassin2 If Max Patkin was an NHL coach...","GarthMcKenzie",],
["5","RT @assassinscreed: Happy New Year, Assassins! In 2015, remember the tenets of The Creed, and continue to serve the light.","giancarloseraf1",],
["5","RT @assassinscreed: Congratulations to our #AC4BlackFlag Freedom Cry and #AssassinsCreed Unity teams on their 2015 #WGAawards nominationsh…","giancarloseraf1",],
],
"pos":[["5.82","RT @caneandrinse: Have an opinion regarding Ubisoft\'s Assassin\'s Creed III? Then leave it here for inclusion in our next podcast:http://t.…","JaySevenZero",],
["7.4","RT @caneandrinse: Whether you love it or loathe it, offer us your Three Word Review for Assassin\'s Creed III #CRTWR","JaySevenZero",],
["7.46","RT @kulpreetvirdi: Congrats @HeathStevens69 you\'ve won my giveaway and this awesome Assassin\'s Creed Black Flag! DM me your details 😊 http:…","V3rmilion_N1nja",],
["5.9","I won 3 achievements in Assassin\'s Creed: Brotherhood for 57 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.6","I won 2 achievements in Assassin\'s Creed: Brotherhood for 49 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.6","I won 2 achievements in Assassin\'s Creed: Brotherhood for 36 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["6.01","I won the Fundraiser achievement in Assassin\'s Creed: Brotherhood for 22 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.14","I won 2 achievements in Assassin\'s Creed: Brotherhood for 45 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.74","I won 2 achievements in Assassin\'s Creed: Brotherhood for 52 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.4","I won the Boom! achievement in Assassin\'s Creed: Brotherhood for 24 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.45","I won the Kaboom! achievement in Assassin\'s Creed: Brotherhood for 24 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
["5.6","I won 2 achievements in Assassin\'s Creed: Brotherhood for 58 #TrueAchievement pts - http://t.co/YAm8ZWIgYH","Xexyzx",],
],
},
"2014-12":{"neg":[["3.55","@StephenKnux Did you enjoy Assassins Creed Unity or did you find something else when Xbox Live went back up?","277sonic",],
["1.44","@StephenKnux Ehhhh Assassins creed Unity is buggy with problems, you might as well get another game, but I heard Black Flag wasn\'t bad","277sonic",],
["4.76","RT @wikileaks: RELEASE: CIA review of High Value Target assassination programs http://t.co/WizWFKg17m press release: http://t.co/irFg0Y64Os","GoXonLine",],
],
"neutral":[["5","RT @xboxuk: 12 Days of Xbox – Day 2!RT for a chance to win an #XboxOne &amp; #ACUnity Notre Dame Edition courtesy of @Assassins_UK! http://t.…","deathbox_",],
["5","RT @wikileaks: CIA warned assassination program might backfire http://t.co/irFg0Y64Os #CIAassassination","GoXonLine",],
["5","@dragonage ASSASSIN bING BANG BOOm fav specialization","j0hke",],
["5","RT @Kotaku: Photos compare the Paris in Assassin\'s Creed Unity to the Paris of 2014 http://t.co/os3kZ0oYQc http://t.co/fKJom1nMGO","blodsvept_",],
],
"pos":[["6.51","I liked a @YouTube video http://t.co/FjmhF9bOEX Multiplayer Trailer | Assassin\'s Creed 4 Black Flag [North America]","Daftpedro",],
["6.93","RT @Malik4Play: Assassin\'s Creed: Unity Paris is pretty accurate to IRL 2014 Paris. I find it impressive http://t.co/350ABWcQs0 http://t.co…","joeldawson83",],
],
},
"2014-04":{"neg":[["2.83","I wore my Assassin\'s Creed shirt to dodgeball and we lost horribly. Damn assassins, letting me down.","Musikophilia",],
],
"neutral":[],
"pos":[],
},
"2014-10":{"neg":[["2.6","It\'s just me, or Arno Dorian from @assassinscreed Unity looks like the footballer @G_Higuain??","blodsvept_",],
],
"neutral":[["5","Assassin’s Creed Unity: [PEGI 18] Trailer dello spot TV: http://t.co/GWRudKPihb via @YouTube","madK_RinoaHeart",],
["5","RT @IGN: Assassin\'s Creed Rogue is officially heading to PC in early 2015: http://t.co/KDAypC2f4a http://t.co/ZGemXKuRIe","TrollZoares",],
],
"pos":[],
},
"2014-06":{"neg":[["4.86","Getting pumped for #ACUnity.  So decided to mess around with this old thing.I love this thing! #AssassinsCreed http://t.co/506xJew8a7","ShinnRyan",],
],
"neutral":[["5","RT @Bondboy7799: Assassin’s Creed Unity Is Targetting 1080p/60fps On PS4 And Xbox One « http://t.co/9kqjb9kstQ: Video Gam... http://t.co/bX…","DeathlightC7",],
["5","That last shot in the assassins creed trailer was a bit \"boy band\" #420upinthisBITCH","OtherKrab",],
["5","RT @gamespot: Report: Assassin\'s Creed Unity targeting 1080p/60fps on PS4 and Xbox One. http://t.co/DzICr83rRw http://t.co/uzlYqg2OwQ","ShinnRyan",],
["5","Act V in Watch Dogs is giving me nightmarish flashbacks to the end of the first Assassin\'s Creed.","videodiscthings",],
],
"pos":[["5.78","RT @ErrorJustin: If Assassin\'s Creed Comet turns out to be a sailing game as rumored, I\'ll be more excited for it than Unity.","ShinnRyan",],
["5.47","RT @AmazonUK: Exclusive Special Offer: Reply w/ #AmazonBasket to add #ACUnity #PS4: http://t.co/2Gp2X13PYg @Assassins_UK @UbisoftUK http://…","ShinnRyan",],
],
},
"2014-03":{"neg":[],
"neutral":[["5","Men\'s Assassin\'s Creed Style Hoodie | Deal Man http://t.co/FIv9hQQUrV","RageKage5000",],
],
"pos":[["6.49","@assassinscreed @Ubisoft Edward in florence?! :P having fun on my holidays! http://t.co/5HFLHFGdNh","SteoAA",],
],
},
"2014-09":{"neg":[],
"neutral":[["5","@MolksTVTalk My GamePad required games are MarioKart8, Darksiders2, AssassinsCreed4, S.Mario3DWorld and NintendoLand (came with my Wii U)","WillHewett",],
],
"pos":[],
},
"2014-07":{"neg":[["2.93","Those shanties from Assassin\'s Creed IV refuse to escape my mind, I\'m not complaining.  Just need to add the ocean theme from Wind Waker.","videodiscthings",],
],
"neutral":[["5","The templar lady!!!! *_* Assassin’s Creed Unity : http://t.co/5WNMFRC9ZW#ACUnity #Ubisoft #XboxOne","madK_RinoaHeart",],
["5","RT @gamespot: Following the E3 controversy, new Assassin\'s Creed Unity trailer shows off a female character. http://t.co/fiSCXo9M0y http://…","ShinnRyan",],
["5","RT @IGN: Watch as @DestinLegarie and @MitchyD break down the new Assassin\'s Creed Unity trailer. http://t.co/uHlA9rmxI0 http://t.co/nVn9XuJ…","ShinnRyan",],
["5","Assassin\'s Creed IV: Black Flag Swan Dive mishap (PS4): http://t.co/gOemJ8JP3u via @YouTube","videodiscthings",],
],
"pos":[["7.02","I liked a @YouTube video http://t.co/2MoAKYT15n The Assassin\'s Creed Experience at SDCC","videodiscthings",],
],
},
};